"""Add missing tables

Revision ID: ceb70f201aef
Revises: b5f0edeab0da
Create Date: 2026-02-28 09:18:40.375228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ceb70f201aef'
down_revision: Union[str, None] = 'b5f0edeab0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_temperatures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('battery_temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['user_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_vehicle_id', 'first_date', name='uq_battery_temp_vehicle_first')
    )
    op.create_index(op.f('ix_battery_temperatures_user_vehicle_id'), 'battery_temperatures', ['user_vehicle_id'], unique=False)
    op.create_table('charging_powers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['user_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_vehicle_id', 'first_date', name='uq_charging_powers_vehicle_first')
    )
    op.create_index(op.f('ix_charging_powers_user_vehicle_id'), 'charging_powers', ['user_vehicle_id'], unique=False)
    op.create_table('climatization_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['user_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_vehicle_id', 'first_date', name='uq_climatization_states_vehicle_first')
    )
    op.create_index(op.f('ix_climatization_states_user_vehicle_id'), 'climatization_states', ['user_vehicle_id'], unique=False)
    op.create_table('outside_temperatures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outside_temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['user_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_vehicle_id', 'first_date', name='uq_outside_temp_vehicle_first')
    )
    op.create_index(op.f('ix_outside_temperatures_user_vehicle_id'), 'outside_temperatures', ['user_vehicle_id'], unique=False)
    op.create_table('weconnect_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_vehicle_id'], ['user_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_vehicle_id', 'datetime', name='uq_weconnect_errors_vehicle_dt')
    )
    op.create_index(op.f('ix_weconnect_errors_user_vehicle_id'), 'weconnect_errors', ['user_vehicle_id'], unique=False)
    op.create_table('drive_consumptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('drive_id', sa.BigInteger(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'first_date', name='uq_dc_drive_first')
    )
    op.create_index(op.f('ix_drive_consumptions_drive_id'), 'drive_consumptions', ['drive_id'], unique=False)
    op.create_table('drive_ranges_estimated_full',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('drive_id', sa.BigInteger(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_estimated_full', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'first_date', name='uq_dr_estimated_full_drive_first')
    )
    op.create_index(op.f('ix_drive_ranges_estimated_full_drive_id'), 'drive_ranges_estimated_full', ['drive_id'], unique=False)
    op.drop_constraint('fk_charging_sessions_location', 'charging_sessions', type_='foreignkey')
    op.drop_constraint('fk_charging_sessions_charging_station', 'charging_sessions', type_='foreignkey')
    op.drop_constraint('fk_trips_destination_location', 'trips', type_='foreignkey')
    op.drop_constraint('fk_trips_start_location', 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_locations_external_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_charging_stations_external_id'), table_name='charging_stations')
    op.drop_table('charging_stations')
    op.drop_column('charging_sessions', 'real_cost')
    op.drop_column('charging_sessions', 'location_id')
    op.drop_column('charging_sessions', 'session_charge_type')
    op.drop_column('charging_sessions', 'real_charged')
    op.drop_column('charging_sessions', 'plug_connected_date')
    op.drop_column('charging_sessions', 'charging_station_id')
    op.drop_column('trips', 'destination_position_longitude')
    op.drop_column('trips', 'start_location_id')
    op.drop_column('trips', 'destination_location_id')
    op.drop_column('trips', 'start_position_latitude')
    op.drop_column('trips', 'start_position_longitude')
    op.drop_column('trips', 'destination_position_latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('destination_position_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_position_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_position_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('destination_location_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_location_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('destination_position_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_trips_start_location'), 'trips', 'locations', ['start_location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_trips_destination_location'), 'trips', 'locations', ['destination_location_id'], ['id'], ondelete='SET NULL')
    op.add_column('charging_sessions', sa.Column('charging_station_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('charging_sessions', sa.Column('plug_connected_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('charging_sessions', sa.Column('real_charged', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('charging_sessions', sa.Column('session_charge_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('charging_sessions', sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('charging_sessions', sa.Column('real_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_charging_sessions_charging_station'), 'charging_sessions', 'charging_stations', ['charging_station_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_charging_sessions_location'), 'charging_sessions', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_table('charging_stations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('max_power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('num_spots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operator_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operator_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('charging_stations_pkey'))
    )
    op.create_index(op.f('ix_charging_stations_external_id'), 'charging_stations', ['external_id'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amenity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('house_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('road', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('neighbourhood', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state_district', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_index(op.f('ix_locations_external_id'), 'locations', ['external_id'], unique=True)
    op.drop_index(op.f('ix_drive_ranges_estimated_full_drive_id'), table_name='drive_ranges_estimated_full')
    op.drop_table('drive_ranges_estimated_full')
    op.drop_index(op.f('ix_drive_consumptions_drive_id'), table_name='drive_consumptions')
    op.drop_table('drive_consumptions')
    op.drop_index(op.f('ix_weconnect_errors_user_vehicle_id'), table_name='weconnect_errors')
    op.drop_table('weconnect_errors')
    op.drop_index(op.f('ix_outside_temperatures_user_vehicle_id'), table_name='outside_temperatures')
    op.drop_table('outside_temperatures')
    op.drop_index(op.f('ix_climatization_states_user_vehicle_id'), table_name='climatization_states')
    op.drop_table('climatization_states')
    op.drop_index(op.f('ix_charging_powers_user_vehicle_id'), table_name='charging_powers')
    op.drop_table('charging_powers')
    op.drop_index(op.f('ix_battery_temperatures_user_vehicle_id'), table_name='battery_temperatures')
    op.drop_table('battery_temperatures')
    # ### end Alembic commands ###
