"""add_superuser_and_invite_requests

Revision ID: de8349efe7f2
Revises: a1b2c3d4e5f6
Create Date: 2026-03-02 07:34:20.606813
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de8349efe7f2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_requests_email'), 'invite_requests', ['email'], unique=True)
    op.create_index(op.f('ix_invite_requests_token'), 'invite_requests', ['token'], unique=True)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_invite_requests_token'), table_name='invite_requests')
    op.drop_index(op.f('ix_invite_requests_email'), table_name='invite_requests')
    op.drop_table('invite_requests')
    # ### end Alembic commands ###
